# Generated by Django 5.2.12 on 2026-04-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='images/')),
                ('files', models.FileField(upload_to='files/')),
                ('video', models.FileField(upload_to='video/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
